apiVersion: v1
kind: Service
metadata:
  name: sample-metrics-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '8080'
spec:
  selector:
    app: sample-metrics
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080